"""
NSE Portfolio Tracker – Streamlit Dashboard
============================================
Run with:  streamlit run streamlit_dashboard.py

This dashboard reads from:
  1. An uploaded output Excel file (generated by your existing Python script), OR
  2. Automatically from the reports/ folder (if files exist there)

It displays: Portfolio summary, NSE prices, charts, risk analysis,
rebalancing suggestions, dividends, and performance history.
"""

import os
import glob
import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

# ─── Page config ───────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="NSE Portfolio Tracker",
    page_icon="📈",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ─── Colour palette (mirrors your existing script theme) ───────────────────────
DARK_OLIVE   = "#3B4436"
CREAM        = "#F1E9CB"
TEXT_DARK    = "#2F332E"
WARM_BEIGE   = "#E6DFD3"
WARM_WHITE   = "#FDFBF7"
SOFT_BEIGE   = "#EAECE6"
BORDER_COLOR = "#B8AA91"
ACCENT       = "#7A8C6E"

# ─── Custom CSS ────────────────────────────────────────────────────────────────
st.markdown(f"""
<style>
  @import url('https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;600;700&family=Source+Sans+3:wght@300;400;600&display=swap');

  html, body, [class*="css"] {{
      font-family: 'Source Sans 3', sans-serif;
      background-color: {WARM_WHITE};
      color: {TEXT_DARK};
  }}

  /* Sidebar */
  section[data-testid="stSidebar"] {{
      background-color: {DARK_OLIVE} !important;
  }}
  section[data-testid="stSidebar"] * {{
      color: {CREAM} !important;
  }}
  section[data-testid="stSidebar"] .stRadio label {{
      color: {CREAM} !important;
  }}

  /* Main header */
  .main-header {{
      font-family: 'Playfair Display', serif;
      font-size: 2.4rem;
      font-weight: 700;
      color: {DARK_OLIVE};
      border-bottom: 3px solid {DARK_OLIVE};
      padding-bottom: 0.4rem;
      margin-bottom: 1.5rem;
  }}
  .section-title {{
      font-family: 'Playfair Display', serif;
      font-size: 1.3rem;
      font-weight: 600;
      color: {DARK_OLIVE};
      margin-top: 2rem;
      margin-bottom: 0.6rem;
      border-left: 4px solid {ACCENT};
      padding-left: 0.6rem;
  }}

  /* KPI cards */
  .kpi-card {{
      background: {SOFT_BEIGE};
      border: 1px solid {BORDER_COLOR};
      border-radius: 10px;
      padding: 1.2rem 1.4rem;
      text-align: center;
  }}
  .kpi-label {{
      font-size: 0.82rem;
      font-weight: 600;
      letter-spacing: 0.08em;
      text-transform: uppercase;
      color: {ACCENT};
      margin-bottom: 0.3rem;
  }}
  .kpi-value {{
      font-family: 'Playfair Display', serif;
      font-size: 1.7rem;
      font-weight: 700;
      color: {DARK_OLIVE};
  }}
  .kpi-sub {{
      font-size: 0.78rem;
      color: {ACCENT};
      margin-top: 0.2rem;
  }}

  /* Status badges */
  .badge-ok  {{ background:#d4edda; color:#155724; padding:3px 10px; border-radius:12px; font-size:0.8rem; }}
  .badge-warn{{ background:#fff3cd; color:#856404; padding:3px 10px; border-radius:12px; font-size:0.8rem; }}
  .badge-bad {{ background:#f8d7da; color:#721c24; padding:3px 10px; border-radius:12px; font-size:0.8rem; }}

  /* DataFrames */
  .stDataFrame {{ border: 1px solid {BORDER_COLOR}; border-radius: 8px; overflow: hidden; }}

  /* Plotly chart border */
  .js-plotly-plot {{ border-radius: 10px; overflow: hidden; }}

  /* Remove default top padding */
  .block-container {{ padding-top: 1.5rem; }}

  /* Metric delta colours */
  [data-testid="stMetricDelta"] {{ font-size: 0.85rem; }}
</style>
""", unsafe_allow_html=True)


# ═══════════════════════════════════════════════════════════════════════════════
# HELPERS
# ═══════════════════════════════════════════════════════════════════════════════

SHEET_NAMES = {
    "dashboard" : "Dashboard1",
    "holdings"  : "Holdings",
    "nse"       : "NSE_Prices",
    "dividends" : "Dividends",
    "history"   : "Performance History",
    "tx"        : "Transactions",
}

@st.cache_data(show_spinner=False)
def load_workbook_sheets(file_bytes_or_path, is_path=False):
    """Load all relevant sheets from the output Excel workbook."""
    sheets = {}
    try:
        src = file_bytes_or_path if is_path else file_bytes_or_path
        xl  = pd.ExcelFile(src)
        for key, name in SHEET_NAMES.items():
            if name in xl.sheet_names:
                sheets[key] = pd.read_excel(src, sheet_name=name)
            else:
                sheets[key] = pd.DataFrame()
    except Exception as e:
        st.error(f"Could not read workbook: {e}")
    return sheets


def fmt_kes(val):
    try:
        return f"KES {float(val):,.2f}"
    except Exception:
        return str(val)


def fmt_pct(val):
    try:
        return f"{float(val):.2f}%"
    except Exception:
        return str(val)


def plotly_pie(df, names_col, values_col, title):
    fig = px.pie(
        df, names=names_col, values=values_col, title=title,
        color_discrete_sequence=px.colors.sequential.Darkmint,
        hole=0.35,
    )
    fig.update_traces(textposition="outside", textinfo="percent+label")
    fig.update_layout(
        paper_bgcolor="rgba(0,0,0,0)",
        plot_bgcolor ="rgba(0,0,0,0)",
        font_color  =TEXT_DARK,
        title_font  =dict(family="Playfair Display", size=16, color=DARK_OLIVE),
        margin      =dict(t=60, b=20, l=20, r=20),
        legend      =dict(font=dict(size=11)),
    )
    return fig


def plotly_bar(df, x_col, y_col, title, color=DARK_OLIVE):
    fig = px.bar(
        df, x=x_col, y=y_col, title=title,
        color_discrete_sequence=[color],
        text=y_col,
    )
    fig.update_traces(texttemplate="%{text:.1f}%", textposition="outside")
    fig.update_layout(
        paper_bgcolor="rgba(0,0,0,0)",
        plot_bgcolor ="rgba(0,0,0,0)",
        font_color  =TEXT_DARK,
        title_font  =dict(family="Playfair Display", size=16, color=DARK_OLIVE),
        xaxis_tickangle=-35,
        margin=dict(t=60, b=60, l=20, r=20),
        yaxis_title="Allocation %",
    )
    return fig


def plotly_line(df, x_col, y_col, title):
    fig = go.Figure()
    fig.add_trace(go.Scatter(
        x=df[x_col], y=df[y_col],
        mode="lines+markers",
        line=dict(color=DARK_OLIVE, width=2.5),
        marker=dict(size=6, color=ACCENT),
        fill="tozeroy",
        fillcolor=f"rgba(59,68,54,0.08)",
    ))
    fig.update_layout(
        title=dict(text=title, font=dict(family="Playfair Display", size=16, color=DARK_OLIVE)),
        paper_bgcolor="rgba(0,0,0,0)",
        plot_bgcolor ="rgba(0,0,0,0)",
        font_color  =TEXT_DARK,
        xaxis_title =x_col,
        yaxis_title ="Portfolio Value (KES)",
        margin      =dict(t=60, b=40, l=20, r=20),
        hovermode   ="x unified",
    )
    return fig


def kpi_card(label, value, sub=""):
    sub_html = f'<div class="kpi-sub">{sub}</div>' if sub else ""
    return f"""
    <div class="kpi-card">
        <div class="kpi-label">{label}</div>
        <div class="kpi-value">{value}</div>
        {sub_html}
    </div>"""


def style_dataframe(df):
    """Return a styled dataframe with the portfolio colour theme."""
    return df.style.set_properties(**{
        "background-color": WARM_WHITE,
        "color"           : TEXT_DARK,
        "border"          : f"1px solid {BORDER_COLOR}",
        "font-size"       : "13px",
    }).set_table_styles([{
        "selector": "th",
        "props"   : [
            ("background-color", DARK_OLIVE),
            ("color", CREAM),
            ("font-family", "Playfair Display, serif"),
            ("font-size", "13px"),
            ("padding", "8px 12px"),
        ],
    }])


# ═══════════════════════════════════════════════════════════════════════════════
# SIDEBAR – data source
# ═══════════════════════════════════════════════════════════════════════════════

with st.sidebar:
    st.markdown("## 📊 NSE Portfolio Tracker")
    st.markdown("---")
    st.markdown("**Data Source**")

    source_mode = st.radio(
        "Load data from:",
        ["Upload Excel file", "Auto-read from reports/ folder"],
        label_visibility="collapsed",
    )

    sheets = {}

    if source_mode == "Upload Excel file":
        uploaded = st.file_uploader(
            "Upload your output Excel file",
            type=["xlsx"],
            help="Upload the *_Dashboard_Output.xlsx file generated by your Python script.",
        )
        if uploaded:
            sheets = load_workbook_sheets(uploaded)
            st.success(f"✅ Loaded: {uploaded.name}")

    else:  # Auto-read from reports/
        reports_dir = "reports"
        xlsx_files  = glob.glob(os.path.join(reports_dir, "*_Dashboard_Output.xlsx"))

        if not xlsx_files:
            st.warning(f"No output files found in `{reports_dir}/`.\nRun your Python script first, or switch to Upload mode.")
        else:
            chosen = st.selectbox(
                "Select portfolio file:",
                [os.path.basename(f) for f in xlsx_files],
            )
            chosen_path = os.path.join(reports_dir, chosen)
            sheets = load_workbook_sheets(chosen_path, is_path=True)
            st.success(f"✅ Loaded: {chosen}")

    st.markdown("---")
    st.markdown("**Navigation**")
    page = st.radio(
        "Go to:",
        [
            "📈 Portfolio Summary",
            "🏦 NSE Live Prices",
            "🥧 Allocation Charts",
            "⚠️ Risk & Rebalancing",
            "🎛️ Risk Settings",
            "💰 Dividends",
            "📅 Performance History",
            "🔄 Transactions",
            "📧 Reports & Email",
        ],
        label_visibility="collapsed",
    )
    st.markdown("---")
    st.caption("Dashboard reads your existing script's output.\nRun your Python script to refresh data.")


# ═══════════════════════════════════════════════════════════════════════════════
# NO DATA STATE
# ═══════════════════════════════════════════════════════════════════════════════

if not sheets:
    st.markdown('<div class="main-header">📈 NSE Portfolio Tracker</div>', unsafe_allow_html=True)
    st.info(
        "👈 **Get started:** Upload your `*_Dashboard_Output.xlsx` file in the sidebar, "
        "or run your Python script so files appear in the `reports/` folder, "
        "then select 'Auto-read from reports/ folder'.",
        icon="📂",
    )
    st.stop()


# ═══════════════════════════════════════════════════════════════════════════════
# PAGE: PORTFOLIO SUMMARY
# ═══════════════════════════════════════════════════════════════════════════════

if page == "📈 Portfolio Summary":
    st.markdown('<div class="main-header">📈 Portfolio Summary</div>', unsafe_allow_html=True)

    dash_df     = sheets.get("dashboard", pd.DataFrame())
    holdings_df = sheets.get("holdings",  pd.DataFrame())

    # ── KPI cards ──────────────────────────────────────────────────────────────
    total_val   = 0
    num_assets  = 0
    num_sectors = 0

    if not dash_df.empty:
        # Dashboard1 sheet has summary rows at top
        for _, row in dash_df.iterrows():
            metric = str(row.get("Metric", "")).strip()
            value  = row.get("Value", 0)
            if "Total Portfolio Value" in metric:
                try:    total_val = float(value)
                except: pass
            elif "Number of Assets" in metric:
                try:    num_assets = int(value)
                except: pass
            elif "Number of Sectors" in metric:
                try:    num_sectors = int(value)
                except: pass

    if total_val == 0 and not holdings_df.empty and "Market Value" in holdings_df.columns:
        total_val   = pd.to_numeric(holdings_df["Market Value"], errors="coerce").sum()
        num_assets  = len(holdings_df)
        num_sectors = holdings_df["Sector"].nunique() if "Sector" in holdings_df.columns else 0

    col1, col2, col3 = st.columns(3)
    with col1:
        st.markdown(kpi_card("Total Portfolio Value", fmt_kes(total_val)), unsafe_allow_html=True)
    with col2:
        st.markdown(kpi_card("Holdings", str(num_assets), "individual assets"), unsafe_allow_html=True)
    with col3:
        st.markdown(kpi_card("Sectors", str(num_sectors), "diversified sectors"), unsafe_allow_html=True)

    # ── Holdings table ─────────────────────────────────────────────────────────
    if not holdings_df.empty:
        st.markdown('<div class="section-title">All Holdings</div>', unsafe_allow_html=True)

        display_cols = [c for c in [
            "Asset", "Sector", "Shares", "Buy Price", "Current Price",
            "Market Value", "Asset Allocation %", "Average Return %",
            "Gain/Loss", "Price Source",
        ] if c in holdings_df.columns]

        show_df = holdings_df[display_cols].copy()

        # Format money columns
        for col in ["Buy Price", "Current Price", "Market Value", "Gain/Loss"]:
            if col in show_df.columns:
                show_df[col] = pd.to_numeric(show_df[col], errors="coerce").map(
                    lambda x: f"KES {x:,.2f}" if pd.notna(x) else ""
                )
        for col in ["Asset Allocation %", "Average Return %"]:
            if col in show_df.columns:
                show_df[col] = pd.to_numeric(show_df[col], errors="coerce").map(
                    lambda x: f"{x:.2f}%" if pd.notna(x) else ""
                )

        st.dataframe(show_df, use_container_width=True, hide_index=True)
    else:
        st.warning("Holdings sheet not found or empty in this file.")


# ═══════════════════════════════════════════════════════════════════════════════
# PAGE: NSE LIVE PRICES
# ═══════════════════════════════════════════════════════════════════════════════

elif page == "🏦 NSE Live Prices":
    st.markdown('<div class="main-header">🏦 NSE Live Prices</div>', unsafe_allow_html=True)

    nse_df = sheets.get("nse", pd.DataFrame())

    if nse_df.empty:
        st.warning("NSE_Prices sheet not found in this file.")
    else:
        st.markdown('<div class="section-title">Nairobi Securities Exchange – Price Snapshot</div>', unsafe_allow_html=True)

        # Price source badge
        if "Price Source" in nse_df.columns:
            sources = nse_df["Price Source"].unique()
            for src in sources:
                badge = "badge-ok" if "unavailable" not in str(src).lower() else "badge-bad"
                st.markdown(f'<span class="{badge}">Source: {src}</span>', unsafe_allow_html=True)
            st.markdown("")

        # Last updated
        if "Last Updated" in nse_df.columns:
            updated = nse_df["Last Updated"].dropna().iloc[0] if not nse_df["Last Updated"].dropna().empty else ""
            if updated:
                st.caption(f"🕐 Prices last fetched: {updated}")

        # Display table
        show_df = nse_df.copy()
        if "NSE Price" in show_df.columns:
            show_df["NSE Price"] = pd.to_numeric(show_df["NSE Price"], errors="coerce").map(
                lambda x: f"KES {x:,.2f}" if pd.notna(x) else "Unavailable"
            )

        st.dataframe(show_df, use_container_width=True, hide_index=True)

        # Mini bar chart of prices
        price_data = nse_df.copy()
        if "NSE Price" in price_data.columns and "Asset" in price_data.columns:
            price_data["NSE Price"] = pd.to_numeric(price_data["NSE Price"], errors="coerce")
            price_data = price_data.dropna(subset=["NSE Price"])
            if not price_data.empty:
                st.markdown('<div class="section-title">Price Comparison</div>', unsafe_allow_html=True)
                fig = px.bar(
                    price_data, x="Asset", y="NSE Price",
                    color_discrete_sequence=[DARK_OLIVE],
                    labels={"NSE Price": "Price (KES)"},
                    title="Current NSE Prices by Asset",
                    text="NSE Price",
                )
                fig.update_traces(texttemplate="KES %{text:,.2f}", textposition="outside")
                fig.update_layout(
                    paper_bgcolor="rgba(0,0,0,0)",
                    plot_bgcolor ="rgba(0,0,0,0)",
                    font_color  =TEXT_DARK,
                    title_font  =dict(family="Playfair Display", size=16, color=DARK_OLIVE),
                    margin      =dict(t=60, b=60),
                    xaxis_tickangle=-30,
                )
                st.plotly_chart(fig, use_container_width=True)


# ═══════════════════════════════════════════════════════════════════════════════
# PAGE: ALLOCATION CHARTS
# ═══════════════════════════════════════════════════════════════════════════════

elif page == "🥧 Allocation Charts":
    st.markdown('<div class="main-header">🥧 Allocation Charts</div>', unsafe_allow_html=True)

    holdings_df = sheets.get("holdings", pd.DataFrame())

    if holdings_df.empty:
        st.warning("Holdings data not found.")
    else:
        col_left, col_right = st.columns(2)

        # ── Asset Pie ──────────────────────────────────────────────────────────
        with col_left:
            st.markdown('<div class="section-title">Asset Allocation</div>', unsafe_allow_html=True)
            if "Asset" in holdings_df.columns and "Market Value" in holdings_df.columns:
                asset_data = holdings_df[["Asset", "Market Value"]].copy()
                asset_data["Market Value"] = pd.to_numeric(asset_data["Market Value"], errors="coerce")
                asset_data = asset_data.dropna(subset=["Market Value"])
                asset_data = asset_data[asset_data["Market Value"] > 0]
                if not asset_data.empty:
                    fig = plotly_pie(asset_data, "Asset", "Market Value", "Asset Allocation by Market Value")
                    st.plotly_chart(fig, use_container_width=True)
                else:
                    st.info("No positive market values to display.")

        # ── Sector Bar ────────────────────────────────────────────────────────
        with col_right:
            st.markdown('<div class="section-title">Sector Allocation</div>', unsafe_allow_html=True)
            if "Sector" in holdings_df.columns and "Market Value" in holdings_df.columns:
                sector_data = holdings_df.copy()
                sector_data["Market Value"] = pd.to_numeric(sector_data["Market Value"], errors="coerce")
                sector_data = sector_data.dropna(subset=["Market Value"])
                total = sector_data["Market Value"].sum()
                sector_grouped = sector_data.groupby("Sector")["Market Value"].sum().reset_index()
                if total > 0:
                    sector_grouped["Allocation %"] = (sector_grouped["Market Value"] / total * 100).round(2)
                else:
                    sector_grouped["Allocation %"] = 0
                if not sector_grouped.empty:
                    fig = plotly_bar(sector_grouped, "Sector", "Allocation %", "Sector Allocation %")
                    st.plotly_chart(fig, use_container_width=True)

        # ── Sector Pie ────────────────────────────────────────────────────────
        st.markdown('<div class="section-title">Sector Value Distribution</div>', unsafe_allow_html=True)
        if "Sector" in holdings_df.columns and "Market Value" in holdings_df.columns:
            sector_data2 = holdings_df.copy()
            sector_data2["Market Value"] = pd.to_numeric(sector_data2["Market Value"], errors="coerce")
            sector_grouped2 = sector_data2.groupby("Sector")["Market Value"].sum().reset_index()
            sector_grouped2 = sector_grouped2[sector_grouped2["Market Value"] > 0]
            if not sector_grouped2.empty:
                fig2 = plotly_pie(sector_grouped2, "Sector", "Market Value", "Sector Value Distribution")
                st.plotly_chart(fig2, use_container_width=True)

        # ── Top holdings table ────────────────────────────────────────────────
        st.markdown('<div class="section-title">Top 5 Holdings by Value</div>', unsafe_allow_html=True)
        if "Asset" in holdings_df.columns and "Market Value" in holdings_df.columns:
            top5 = holdings_df[["Asset", "Sector", "Market Value", "Asset Allocation %"]].copy()
            top5["Market Value"] = pd.to_numeric(top5["Market Value"], errors="coerce")
            top5 = top5.sort_values("Market Value", ascending=False).head(5)
            top5["Market Value"] = top5["Market Value"].map(lambda x: f"KES {x:,.2f}" if pd.notna(x) else "")
            if "Asset Allocation %" in top5.columns:
                top5["Asset Allocation %"] = pd.to_numeric(top5["Asset Allocation %"], errors="coerce").map(
                    lambda x: f"{x:.2f}%" if pd.notna(x) else ""
                )
            st.dataframe(top5, use_container_width=True, hide_index=True)


# ═══════════════════════════════════════════════════════════════════════════════
# PAGE: RISK & REBALANCING
# ═══════════════════════════════════════════════════════════════════════════════

elif page == "⚠️ Risk & Rebalancing":
    st.markdown('<div class="main-header">⚠️ Risk & Rebalancing</div>', unsafe_allow_html=True)

    dash_df = sheets.get("dashboard", pd.DataFrame())

    if dash_df.empty:
        st.warning("Dashboard sheet not found.")
    else:
        # The dashboard sheet has multiple stacked tables — parse by header keywords
        def extract_table_by_header(df, keyword):
            """Find a sub-table within Dashboard1 by searching for a column header keyword.
            Handles duplicate column names by working with raw positional values."""
            raw = df.values.tolist()   # work with plain Python lists — no Index issues

            for row_idx, row in enumerate(raw):
                str_vals = [str(v).strip() for v in row if v is not None and str(v).strip() not in ("", "nan")]
                if not str_vals:
                    continue
                if any(keyword.lower() in v.lower() for v in str_vals):
                    # This row is the header; make column names unique if needed
                    headers = []
                    seen = {}
                    for v in row:
                        col = str(v).strip() if (v is not None and str(v).strip() not in ("", "nan")) else ""
                        if col in seen:
                            seen[col] += 1
                            col = f"{col}.{seen[col]}"
                        else:
                            seen[col] = 0
                        headers.append(col)

                    # Collect data rows until a fully-empty row
                    data_rows = []
                    for data_row in raw[row_idx + 1:]:
                        str_data = [str(v).strip() for v in data_row if v is not None and str(v).strip() not in ("", "nan")]
                        if not str_data:
                            break
                        data_rows.append(data_row)

                    if data_rows:
                        result = pd.DataFrame(data_rows, columns=headers)
                        # Drop fully-empty columns
                        result = result.loc[:, result.columns != ""]
                        return result.reset_index(drop=True)
            return pd.DataFrame()

        # ── Risk Summary ──────────────────────────────────────────────────────
        st.markdown('<div class="section-title">Risk Summary</div>', unsafe_allow_html=True)
        risk_df = extract_table_by_header(dash_df, "Metric")
        if not risk_df.empty:
            # Look for Risk Score value
            risk_score_row = risk_df[risk_df.iloc[:, 0].astype(str).str.contains("Risk Score", na=False)]
            if not risk_score_row.empty:
                score_val = str(risk_score_row.iloc[0, 1]).strip()
                badge_cls = "badge-ok" if score_val == "Low" else "badge-warn" if score_val == "Medium" else "badge-bad"
                st.markdown(f'<span class="{badge_cls}">Overall Risk Level: <b>{score_val}</b></span><br><br>', unsafe_allow_html=True)

            st.dataframe(risk_df.dropna(how="all", axis=1), use_container_width=True, hide_index=True)
        else:
            st.info("Risk summary not found in Dashboard sheet.")

        # ── Asset Violations ──────────────────────────────────────────────────
        st.markdown('<div class="section-title">Asset Concentration Violations</div>', unsafe_allow_html=True)
        asset_viol = extract_table_by_header(dash_df, "Asset Limit %")
        if not asset_viol.empty and len(asset_viol) > 0:
            st.dataframe(asset_viol.dropna(how="all", axis=1), use_container_width=True, hide_index=True)
        else:
            st.markdown('<span class="badge-ok">✅ No asset concentration violations</span>', unsafe_allow_html=True)

        # ── Sector Violations ─────────────────────────────────────────────────
        st.markdown('<div class="section-title">Sector Concentration Violations</div>', unsafe_allow_html=True)
        sector_viol = extract_table_by_header(dash_df, "Sector Weight %")
        if not sector_viol.empty and len(sector_viol) > 0:
            st.dataframe(sector_viol.dropna(how="all", axis=1), use_container_width=True, hide_index=True)
        else:
            st.markdown('<span class="badge-ok">✅ No sector concentration violations</span>', unsafe_allow_html=True)

        # ── Rebalance Plan ────────────────────────────────────────────────────
        st.markdown('<div class="section-title">Holistic Rebalance Suggestion</div>', unsafe_allow_html=True)
        rebal = extract_table_by_header(dash_df, "Estimated Value")
        if not rebal.empty:
            # Colour BUY rows green, SELL rows red
            action_col = [c for c in rebal.columns if "action" in str(c).lower()]
            if action_col:
                def highlight_action(row):
                    action = str(row.get(action_col[0], "")).upper()
                    if action == "BUY":
                        return [f"background-color: #d4edda; color: #155724"] * len(row)
                    elif action == "SELL":
                        return [f"background-color: #f8d7da; color: #721c24"] * len(row)
                    return [""] * len(row)
                st.dataframe(
                    rebal.dropna(how="all", axis=1).style.apply(highlight_action, axis=1),
                    use_container_width=True,
                    hide_index=True,
                )
            else:
                st.dataframe(rebal.dropna(how="all", axis=1), use_container_width=True, hide_index=True)
        else:
            st.markdown('<span class="badge-ok">✅ No rebalancing trades needed</span>', unsafe_allow_html=True)


# ═══════════════════════════════════════════════════════════════════════════════
# PAGE: DIVIDENDS
# ═══════════════════════════════════════════════════════════════════════════════

elif page == "💰 Dividends":
    st.markdown('<div class="main-header">💰 Dividends</div>', unsafe_allow_html=True)

    div_df = sheets.get("dividends", pd.DataFrame())

    if div_df.empty:
        st.warning("Dividends sheet not found. Make sure your input Excel has a 'Dividend Tracking' sheet.")
    else:
        # The dividends sheet has a summary block below the main table
        # Separate them: summary block starts with "Metric"
        summary_start = None
        for i, row in div_df.iterrows():
            if "Metric" in [str(v).strip() for v in row.values if pd.notna(v)]:
                summary_start = i
                break

        main_div = div_df.iloc[:summary_start].copy() if summary_start else div_df.copy()
        main_div = main_div.dropna(how="all")

        # ── Summary KPIs ──────────────────────────────────────────────────────
        if summary_start is not None:
            summary_block = div_df.iloc[summary_start:].copy()
            summary_block.columns = summary_block.iloc[0]
            summary_block = summary_block[1:].dropna(how="all")

            total_div   = 0
            overall_yld = 0
            for _, row in summary_block.iterrows():
                metric = str(row.get("Metric", "")).strip()
                val    = row.get("Value", 0)
                if "Total Annual Dividend" in metric:
                    try: total_div = float(val)
                    except: pass
                elif "Portfolio Dividend Yield" in metric:
                    try: overall_yld = float(val)
                    except: pass

            c1, c2 = st.columns(2)
            with c1:
                st.markdown(kpi_card("Total Annual Dividend", fmt_kes(total_div)), unsafe_allow_html=True)
            with c2:
                st.markdown(kpi_card("Portfolio Dividend Yield", fmt_pct(overall_yld)), unsafe_allow_html=True)
            st.markdown("")

        # ── Main table ────────────────────────────────────────────────────────
        st.markdown('<div class="section-title">Dividend Breakdown by Asset</div>', unsafe_allow_html=True)
        if not main_div.empty:
            fmt_cols = ["Dividend per Share", "Annual Dividend", "Market Value", "Total Dividend", "Shares"]
            for col in fmt_cols:
                if col in main_div.columns:
                    main_div[col] = pd.to_numeric(main_div[col], errors="coerce").map(
                        lambda x: f"KES {x:,.2f}" if pd.notna(x) else ""
                    )
            if "Dividend Yield %" in main_div.columns:
                main_div["Dividend Yield %"] = pd.to_numeric(main_div["Dividend Yield %"], errors="coerce").map(
                    lambda x: f"{x:.2f}%" if pd.notna(x) else ""
                )
            st.dataframe(main_div.dropna(how="all", axis=1), use_container_width=True, hide_index=True)

        # ── Dividend yield bar chart ───────────────────────────────────────────
        raw_div = sheets.get("dividends", pd.DataFrame()).copy()
        if "Asset" in raw_div.columns and "Dividend Yield %" in raw_div.columns:
            chart_data = raw_div[["Asset", "Dividend Yield %"]].copy()
            chart_data["Dividend Yield %"] = pd.to_numeric(chart_data["Dividend Yield %"], errors="coerce")
            chart_data = chart_data.dropna(subset=["Dividend Yield %"])
            if not chart_data.empty:
                st.markdown('<div class="section-title">Dividend Yield by Asset</div>', unsafe_allow_html=True)
                fig = plotly_bar(chart_data, "Asset", "Dividend Yield %", "Dividend Yield % by Asset", color=ACCENT)
                st.plotly_chart(fig, use_container_width=True)


# ═══════════════════════════════════════════════════════════════════════════════
# PAGE: PERFORMANCE HISTORY
# ═══════════════════════════════════════════════════════════════════════════════

elif page == "📅 Performance History":
    st.markdown('<div class="main-header">📅 Performance History</div>', unsafe_allow_html=True)

    hist_df = sheets.get("history", pd.DataFrame())

    if hist_df.empty:
        st.warning("Performance History sheet not found.")
    else:
        # The sheet has multiple stacked tables (history, monthly, quarterly, yearly returns)
        # Split them by detecting header rows
        def split_history_tables(df):
            tables = []
            current_start = None
            current_header = None

            for i, row in df.iterrows():
                vals = [str(v).strip() for v in row.values if pd.notna(v) and str(v).strip()]
                if not vals:
                    if current_start is not None:
                        tables.append((current_header, df.iloc[current_start:i]))
                        current_start = None
                        current_header = None
                    continue

                # Detect if this row is a header row (contains keyword strings, no numeric values)
                is_header = all(
                    not str(v).replace(",", "").replace(".", "").replace("-", "").replace("%", "").isnumeric()
                    for v in vals
                )
                if is_header and current_start is None:
                    current_start  = i
                    current_header = vals

            if current_start is not None:
                tables.append((current_header, df.iloc[current_start:]))

            return tables

        tables = split_history_tables(hist_df)

        for idx, (header_vals, tbl) in enumerate(tables):
            if tbl.empty:
                continue
            sub = tbl.copy()
            sub.columns = sub.iloc[0]
            sub = sub[1:].dropna(how="all").reset_index(drop=True)

            if sub.empty:
                continue

            # Determine which table this is
            col_names = [str(c).strip() for c in sub.columns]

            if "Portfolio Value" in col_names:
                st.markdown('<div class="section-title">Portfolio Value Over Time</div>', unsafe_allow_html=True)

                sub["Portfolio Value"] = pd.to_numeric(sub.get("Portfolio Value", 0), errors="coerce")
                sub["Date"] = pd.to_datetime(sub.get("Date", ""), errors="coerce")
                sub = sub.dropna(subset=["Date", "Portfolio Value"])
                sub = sub.sort_values("Date")

                if len(sub) >= 2:
                    fig = plotly_line(sub, "Date", "Portfolio Value", "Portfolio Value Over Time")
                    st.plotly_chart(fig, use_container_width=True)

                st.dataframe(sub.assign(
                    **{"Portfolio Value": sub["Portfolio Value"].map(lambda x: f"KES {x:,.2f}" if pd.notna(x) else "")}
                ), use_container_width=True, hide_index=True)

            elif "Return %" in col_names:
                period_col = [c for c in col_names if c not in ["Return %"]][0] if len(col_names) > 1 else "Period"
                label = str(period_col)

                if "Month" in label:
                    title = "Monthly Returns"
                elif "Quarter" in label:
                    title = "Quarterly Returns"
                else:
                    title = "Yearly Returns"

                st.markdown(f'<div class="section-title">{title}</div>', unsafe_allow_html=True)

                sub["Return %"] = pd.to_numeric(sub["Return %"], errors="coerce")
                if not sub["Return %"].dropna().empty:
                    colors_list = [DARK_OLIVE if v >= 0 else "#C0392B" for v in sub["Return %"].fillna(0)]
                    fig = go.Figure(go.Bar(
                        x=sub[period_col], y=sub["Return %"],
                        marker_color=colors_list,
                        text=sub["Return %"].map(lambda x: f"{x:.2f}%" if pd.notna(x) else ""),
                        textposition="outside",
                    ))
                    fig.update_layout(
                        paper_bgcolor="rgba(0,0,0,0)",
                        plot_bgcolor ="rgba(0,0,0,0)",
                        font_color  =TEXT_DARK,
                        title_font  =dict(family="Playfair Display", size=16, color=DARK_OLIVE),
                        title       =title,
                        xaxis_tickangle=-30,
                        yaxis_title ="Return %",
                        margin      =dict(t=60, b=60),
                    )
                    st.plotly_chart(fig, use_container_width=True)


# ═══════════════════════════════════════════════════════════════════════════════
# PAGE: TRANSACTIONS
# ═══════════════════════════════════════════════════════════════════════════════

elif page == "🔄 Transactions":
    st.markdown('<div class="main-header">🔄 Transaction History</div>', unsafe_allow_html=True)

    tx_df = sheets.get("tx", pd.DataFrame())

    if tx_df.empty:
        st.warning("Transactions sheet not found.")
    else:
        # Summary metrics
        buys  = tx_df[tx_df.get("Action", pd.Series()).astype(str).str.upper() == "BUY"]  if "Action" in tx_df.columns else pd.DataFrame()
        sells = tx_df[tx_df.get("Action", pd.Series()).astype(str).str.upper() == "SELL"] if "Action" in tx_df.columns else pd.DataFrame()

        c1, c2, c3 = st.columns(3)
        with c1:
            st.markdown(kpi_card("Total Transactions", str(len(tx_df))), unsafe_allow_html=True)
        with c2:
            st.markdown(kpi_card("Buy Orders", str(len(buys))), unsafe_allow_html=True)
        with c3:
            st.markdown(kpi_card("Sell Orders", str(len(sells))), unsafe_allow_html=True)
        st.markdown("")

        # Filter controls
        col_f1, col_f2 = st.columns(2)
        with col_f1:
            if "Action" in tx_df.columns:
                actions = ["All"] + sorted(tx_df["Action"].dropna().unique().tolist())
                selected_action = st.selectbox("Filter by Action:", actions)
            else:
                selected_action = "All"
        with col_f2:
            if "Asset" in tx_df.columns:
                assets = ["All"] + sorted(tx_df["Asset"].dropna().unique().tolist())
                selected_asset = st.selectbox("Filter by Asset:", assets)
            else:
                selected_asset = "All"

        filtered = tx_df.copy()
        if selected_action != "All" and "Action" in filtered.columns:
            filtered = filtered[filtered["Action"] == selected_action]
        if selected_asset != "All" and "Asset" in filtered.columns:
            filtered = filtered[filtered["Asset"] == selected_asset]

        st.markdown('<div class="section-title">Transaction Log</div>', unsafe_allow_html=True)

        # Colour-code by action
        def highlight_tx(row):
            action = str(row.get("Action", "")).upper()
            if action == "BUY":
                return ["background-color:#d4edda; color:#155724"] * len(row)
            elif action == "SELL":
                return ["background-color:#f8d7da; color:#721c24"] * len(row)
            elif action == "OPENING":
                return ["background-color:#d1ecf1; color:#0c5460"] * len(row)
            return [""] * len(row)

        st.dataframe(
            filtered.style.apply(highlight_tx, axis=1),
            use_container_width=True,
            hide_index=True,
        )

        # Realised gain chart
        if "Realized Gain" in tx_df.columns and "Asset" in tx_df.columns:
            gain_data = tx_df.groupby("Asset")["Realized Gain"].sum().reset_index()
            gain_data["Realized Gain"] = pd.to_numeric(gain_data["Realized Gain"], errors="coerce").fillna(0)
            gain_data = gain_data[gain_data["Realized Gain"] != 0]
            if not gain_data.empty:
                st.markdown('<div class="section-title">Realised Gain / Loss by Asset</div>', unsafe_allow_html=True)
                colors_gain = [DARK_OLIVE if v >= 0 else "#C0392B" for v in gain_data["Realized Gain"]]
                fig = go.Figure(go.Bar(
                    x=gain_data["Asset"], y=gain_data["Realized Gain"],
                    marker_color=colors_gain,
                    text=gain_data["Realized Gain"].map(lambda x: f"KES {x:,.2f}"),
                    textposition="outside",
                ))
                fig.update_layout(
                    paper_bgcolor="rgba(0,0,0,0)",
                    plot_bgcolor ="rgba(0,0,0,0)",
                    font_color  =TEXT_DARK,
                    title       ="Realised Gain / Loss by Asset",
                    title_font  =dict(family="Playfair Display", size=16, color=DARK_OLIVE),
                    yaxis_title ="KES",
                    margin      =dict(t=60, b=60),
                )
                st.plotly_chart(fig, use_container_width=True)


# ═══════════════════════════════════════════════════════════════════════════════
# PAGE: RISK SETTINGS
# ═══════════════════════════════════════════════════════════════════════════════

elif page == "🎛️ Risk Settings":
    st.markdown('<div class="main-header">🎛️ Risk Settings</div>', unsafe_allow_html=True)

    st.markdown(
        "Adjust the risk parameters below. The **Diversification Score** updates live "
        "as you change the settings. When you are happy, click **Save to update_portfolio.py** "
        "to apply them to your script — the next time you run your script it will use these values.",
        unsafe_allow_html=False,
    )

    holdings_df = sheets.get("holdings", pd.DataFrame())

    # ── Default values (matching your hardcoded script defaults) ──────────────
    DEFAULT_SECTOR_LIMIT = 20
    DEFAULT_ASSET_LIMIT  = 10
    DEFAULT_EXCLUSIONS   = ["Cash", "Fixed Income"]
    ALL_SECTORS = sorted(holdings_df["Sector"].dropna().unique().tolist()) if (
        not holdings_df.empty and "Sector" in holdings_df.columns
    ) else ["Cash", "Fixed Income", "Banking", "Insurance", "Telecom", "Energy", "ETF"]

    st.markdown('<div class="section-title">Parameter Controls</div>', unsafe_allow_html=True)

    col_left, col_right = st.columns([1, 1])

    with col_left:
        sector_limit = st.slider(
            "🏦 Sector Weight Limit (%)",
            min_value=5, max_value=50, value=DEFAULT_SECTOR_LIMIT, step=1,
            help="Maximum % of total portfolio that any single sector can occupy "
                 "(excluding risk-excluded sectors like Cash).",
        )
        asset_limit = st.slider(
            "📌 Single Asset Cap (%)",
            min_value=2, max_value=30, value=DEFAULT_ASSET_LIMIT, step=1,
            help="Hard cap on any individual asset. "
                 "Dynamic per-asset limit = Sector Limit ÷ number of assets in sector, "
                 "clipped to this value.",
        )

    with col_right:
        exclusions = st.multiselect(
            "🚫 Sectors excluded from risk calculations",
            options=ALL_SECTORS if ALL_SECTORS else DEFAULT_EXCLUSIONS,
            default=[s for s in DEFAULT_EXCLUSIONS if s in (ALL_SECTORS or DEFAULT_EXCLUSIONS)],
            help="These sectors are ignored when checking concentration limits "
                 "(e.g. Cash and Fixed Income are stable so they don't need capping).",
        )

    # ── Live Diversification Score ────────────────────────────────────────────
    st.markdown('<div class="section-title">Live Diversification Score</div>', unsafe_allow_html=True)

    def compute_live_score(holdings, sector_lim, asset_lim, excl):
        """Recompute diversification score from holdings using the given parameters.

        Scoring logic:
          - Start at 100
          - Each asset violation:  deduct 10 pts flat + 1 pt per % of excess
          - Each sector violation: deduct 10 pts flat + 1 pt per % of excess
          - Clamp to [0, 100]
        Even one large violation with tight limits will significantly tank the score.
        """
        if holdings.empty or "Sector" not in holdings.columns or "Market Value" not in holdings.columns:
            return None, pd.DataFrame(), pd.DataFrame()

        h = holdings.copy()
        h["Market Value"] = pd.to_numeric(h["Market Value"], errors="coerce").fillna(0)
        total = h["Market Value"].sum()
        if total == 0:
            return 0, pd.DataFrame(), pd.DataFrame()

        # Always recalculate allocation % fresh from market values
        h["_alloc_pct"] = (h["Market Value"] / total) * 100

        risk_pool = h[~h["Sector"].isin(excl)].copy()

        if risk_pool.empty:
            return 100, pd.DataFrame(), pd.DataFrame()

        # Dynamic per-asset limit: sector_limit / assets_in_sector, capped at asset_limit
        sector_counts = risk_pool.groupby("Sector")["Asset"].transform("count")
        risk_pool = risk_pool.copy()
        risk_pool["_asset_limit"] = (sector_lim / sector_counts).clip(upper=asset_lim)

        # Asset violations
        asset_viols_raw = risk_pool[risk_pool["_alloc_pct"] > risk_pool["_asset_limit"]].copy()
        asset_viols_raw["Excess %"] = (
            asset_viols_raw["_alloc_pct"] - asset_viols_raw["_asset_limit"]
        ).round(2)

        asset_viols = asset_viols_raw[["Asset", "Sector"]].copy()
        asset_viols["Asset Allocation %"] = asset_viols_raw["_alloc_pct"].round(2)
        asset_viols["Asset Limit %"]      = asset_viols_raw["_asset_limit"].round(2)
        asset_viols["Excess %"]           = asset_viols_raw["Excess %"]

        # Sector violations
        sector_alloc = risk_pool.groupby("Sector")["Market Value"].sum()
        sector_pct   = (sector_alloc / total * 100).reset_index()
        sector_pct.columns = ["Sector", "Sector Weight %"]
        sector_viols = sector_pct[sector_pct["Sector Weight %"] > sector_lim].copy()
        sector_viols["Limit %"]  = sector_lim
        sector_viols["Excess %"] = (sector_viols["Sector Weight %"] - sector_lim).round(2)
        sector_viols["Sector Weight %"] = sector_viols["Sector Weight %"].round(2)

        # Score: 10 pts flat per violation + 1 pt per % of excess
        penalty = 0
        for _, row in asset_viols.iterrows():
            penalty += 10 + float(row["Excess %"])
        for _, row in sector_viols.iterrows():
            penalty += 10 + float(row["Excess %"])

        score = max(0, min(100, round(100 - penalty)))
        return score, asset_viols.reset_index(drop=True), sector_viols.reset_index(drop=True)

    score, live_asset_viols, live_sector_viols = compute_live_score(
        holdings_df, sector_limit, asset_limit, exclusions
    )

    if score is None:
        st.info("Load a portfolio file to see a live score.")
    else:
        # Score gauge using plotly
        if score >= 85:
            score_color = "#28a745"
            score_label = "Low Risk"
            score_badge = "badge-ok"
        elif score >= 70:
            score_color = "#ffc107"
            score_label = "Medium Risk"
            score_badge = "badge-warn"
        else:
            score_color = "#dc3545"
            score_label = "High Risk"
            score_badge = "badge-bad"

        gauge_fig = go.Figure(go.Indicator(
            mode="gauge+number",
            value=score,
            domain={"x": [0, 1], "y": [0, 1]},
            title={"text": "Diversification Score", "font": {"size": 18, "color": DARK_OLIVE, "family": "Playfair Display"}},
            gauge={
                "axis"     : {"range": [0, 100], "tickwidth": 1, "tickcolor": TEXT_DARK},
                "bar"      : {"color": score_color},
                "bgcolor"  : SOFT_BEIGE,
                "borderwidth": 2,
                "bordercolor": BORDER_COLOR,
                "steps": [
                    {"range": [0,  70], "color": "#fde8ea"},
                    {"range": [70, 85], "color": "#fff8e1"},
                    {"range": [85, 100],"color": "#e8f5e9"},
                ],
                "threshold": {
                    "line" : {"color": DARK_OLIVE, "width": 4},
                    "thickness": 0.75,
                    "value": score,
                },
            },
            number={"suffix": " / 100", "font": {"size": 28, "color": score_color}},
        ))
        gauge_fig.update_layout(
            paper_bgcolor="rgba(0,0,0,0)",
            height=280,
            margin=dict(t=40, b=20, l=40, r=40),
        )

        g_col, info_col = st.columns([1, 1])
        with g_col:
            st.plotly_chart(gauge_fig, use_container_width=True)
        with info_col:
            st.markdown("<br><br>", unsafe_allow_html=True)
            st.markdown(
                f'<span class="{score_badge}" style="font-size:1.1rem; padding:6px 18px;">'
                f'Risk Level: <b>{score_label}</b></span>',
                unsafe_allow_html=True,
            )
            st.markdown("<br>", unsafe_allow_html=True)
            st.markdown(f"**Sector limit:** {sector_limit}%")
            st.markdown(f"**Asset cap:** {asset_limit}%")
            st.markdown(f"**Excluded sectors:** {', '.join(exclusions) if exclusions else 'None'}")
            st.markdown(f"**Asset violations:** {len(live_asset_viols)}")
            st.markdown(f"**Sector violations:** {len(live_sector_viols)}")

        # Violation detail tables
        if not live_asset_viols.empty:
            st.markdown('<div class="section-title">Asset Violations under these settings</div>', unsafe_allow_html=True)
            st.dataframe(live_asset_viols, use_container_width=True, hide_index=True)
        else:
            st.markdown('<span class="badge-ok">✅ No asset violations under these settings</span>', unsafe_allow_html=True)

        st.markdown("")
        if not live_sector_viols.empty:
            st.markdown('<div class="section-title">Sector Violations under these settings</div>', unsafe_allow_html=True)
            st.dataframe(live_sector_viols, use_container_width=True, hide_index=True)
        else:
            st.markdown('<span class="badge-ok">✅ No sector violations under these settings</span>', unsafe_allow_html=True)

    # ── Save to script ─────────────────────────────────────────────────────────
    st.markdown('<div class="section-title">Apply Settings to Your Script</div>', unsafe_allow_html=True)
    st.markdown(
        "Click the button below to write these values into `update_portfolio.py`. "
        "The next time you run your script, it will use them automatically."
    )

    script_path = st.text_input(
        "Path to your update_portfolio.py script:",
        value="update_portfolio.py",
        help="Full or relative path. E.g. C:\\Users\\lawre\\...\\update_portfolio.py",
    )

    if st.button("💾 Save Risk Settings to Script", type="primary"):
        try:
            if not os.path.exists(script_path):
                st.error(f"File not found: `{script_path}`. Please check the path above.")
            else:
                with open(script_path, "r", encoding="utf-8") as f:
                    code = f.read()

                import re as _re

                # Replace SECTOR_WEIGHT_LIMIT
                code = _re.sub(
                    r"^SECTOR_WEIGHT_LIMIT\s*=\s*\d+",
                    f"SECTOR_WEIGHT_LIMIT = {sector_limit}",
                    code, flags=_re.MULTILINE,
                )
                # Replace SINGLE_ASSET_WEIGHT_LIMIT
                code = _re.sub(
                    r"^SINGLE_ASSET_WEIGHT_LIMIT\s*=\s*\d+",
                    f"SINGLE_ASSET_WEIGHT_LIMIT = {asset_limit}",
                    code, flags=_re.MULTILINE,
                )
                # Replace SECTOR_RISK_EXCLUSIONS set literal
                excl_repr = "{" + ", ".join(f'"{e}"' for e in exclusions) + "}"
                code = _re.sub(
                    r'^SECTOR_RISK_EXCLUSIONS\s*=\s*\{[^}]*\}',
                    f"SECTOR_RISK_EXCLUSIONS = {excl_repr}",
                    code, flags=_re.MULTILINE,
                )

                with open(script_path, "w", encoding="utf-8") as f:
                    f.write(code)

                st.success(
                    f"✅ Saved! `update_portfolio.py` now uses:\n"
                    f"- Sector limit: **{sector_limit}%**\n"
                    f"- Asset cap: **{asset_limit}%**\n"
                    f"- Exclusions: **{', '.join(exclusions) if exclusions else 'None'}**\n\n"
                    f"Run your Python script to regenerate the output with the new settings."
                )
        except Exception as e:
            st.error(f"Could not update script: {e}")


# ═══════════════════════════════════════════════════════════════════════════════
# PAGE: REPORTS & EMAIL
# ═══════════════════════════════════════════════════════════════════════════════

elif page == "📧 Reports & Email":
    import datetime as _dt
    import smtplib
    from email.mime.text import MIMEText
    from email.mime.multipart import MIMEMultipart
    from email.mime.base import MIMEBase
    from email import encoders as _encoders

    st.markdown('<div class="main-header">📧 Reports & Email</div>', unsafe_allow_html=True)

    # ── Helper: read .env file into a dict ────────────────────────────────────
    def read_env_file(path=".env"):
        """Parse a .env file and return key-value pairs, ignoring comments/blanks."""
        env = {}
        if not os.path.exists(path):
            return env
        with open(path, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#") or "=" not in line:
                    continue
                key, _, val = line.partition("=")
                env[key.strip()] = val.strip()
        return env

    def write_env_file(updates, path=".env"):
        """Merge updates into an existing .env file, preserving other keys."""
        lines = []
        if os.path.exists(path):
            with open(path, "r", encoding="utf-8") as f:
                lines = f.readlines()
        written = set()
        new_lines = []
        for line in lines:
            key = line.split("=")[0].strip()
            if key in updates:
                new_lines.append(f"{key}={updates[key]}\n")
                written.add(key)
            else:
                new_lines.append(line)
        for key, val in updates.items():
            if key not in written:
                new_lines.append(f"{key}={val}\n")
        with open(path, "w", encoding="utf-8") as f:
            f.writelines(new_lines)

    # Load defaults from .env once — cached in session so edits survive reruns
    if "smtp_config" not in st.session_state:
        env = read_env_file()
        st.session_state.smtp_config = {
            "server"  : env.get("EMAIL_SMTP_SERVER",   "smtp.gmail.com"),
            "port"    : int(env.get("EMAIL_SMTP_PORT", "587")),
            "username": env.get("EMAIL_SMTP_USERNAME", ""),
            "password": env.get("EMAIL_SMTP_PASSWORD", ""),
            "from"    : env.get("EMAIL_FROM",           ""),
            "use_tls" : env.get("EMAIL_USE_TLS", "True").lower() in ("true", "1", "yes"),
        }

    cfg = st.session_state.smtp_config

    # ── Find available PDF reports ─────────────────────────────────────────────
    reports_dir = "reports"
    pdf_files   = glob.glob(os.path.join(reports_dir, "*.pdf"))

    st.markdown('<div class="section-title">Available PDF Reports</div>', unsafe_allow_html=True)

    selected_pdf      = None
    selected_pdf_name = None

    if not pdf_files:
        st.warning(
            f"No PDF reports found in `{reports_dir}/`. "
            "Run your Python script first to generate them."
        )
    else:
        pdf_names = [os.path.basename(p) for p in pdf_files]
        selected_pdf_name = st.selectbox("Select a report to send:", pdf_names)
        selected_pdf      = os.path.join(reports_dir, selected_pdf_name)

        if selected_pdf and os.path.exists(selected_pdf):
            size_kb  = os.path.getsize(selected_pdf) / 1024
            mod_time = _dt.datetime.fromtimestamp(
                os.path.getmtime(selected_pdf)
            ).strftime("%Y-%m-%d %H:%M:%S")
            ic1, ic2 = st.columns(2)
            with ic1:
                st.markdown(kpi_card("File Size", f"{size_kb:.1f} KB"), unsafe_allow_html=True)
            with ic2:
                st.markdown(kpi_card("Generated", mod_time), unsafe_allow_html=True)
            st.markdown("")

            with open(selected_pdf, "rb") as _f:
                st.download_button(
                    label     ="⬇️  Download Report PDF",
                    data      =_f.read(),
                    file_name =selected_pdf_name,
                    mime      ="application/pdf",
                )

    # ── Email Configuration (collapsed by default, loaded from .env) ──────────
    st.markdown('<div class="section-title">Email Configuration</div>', unsafe_allow_html=True)

    # Show a read-only summary of current config with an Edit button
    config_loaded = bool(cfg["username"])
    if config_loaded:
        st.markdown(
            f"Using configuration loaded from `.env`  "
            f"**From:** `{cfg['from'] or cfg['username']}`  ·  "
            f"**Server:** `{cfg['server']}:{cfg['port']}`  ·  "
            f"**TLS:** `{cfg['use_tls']}`"
        )
    else:
        st.info("No SMTP configuration found in `.env`. Fill in the form below and save it.")

    if "show_smtp_form" not in st.session_state:
        st.session_state.show_smtp_form = not config_loaded   # auto-open if nothing loaded

    toggle_label = "🔒 Hide Configuration" if st.session_state.show_smtp_form else "✏️ Edit Configuration"
    if st.button(toggle_label, key="toggle_smtp"):
        st.session_state.show_smtp_form = not st.session_state.show_smtp_form
        st.rerun()

    if st.session_state.show_smtp_form:
        with st.container():
            st.markdown("")
            fc1, fc2 = st.columns(2)
            with fc1:
                new_server   = st.text_input("SMTP Server",                          value=cfg["server"])
                new_username = st.text_input("SMTP Username (your email address)",   value=cfg["username"])
                new_from     = st.text_input("From address (blank = use username)",  value=cfg["from"])
            with fc2:
                new_port     = st.number_input("SMTP Port", value=cfg["port"], step=1)
                new_password = st.text_input("SMTP Password / App Password",         value=cfg["password"], type="password")
                new_tls      = st.checkbox("Use TLS", value=cfg["use_tls"])

            st.caption(
                "💡 **Gmail users:** Use an App Password, not your regular password. "
                "Google Account → Security → 2-Step Verification → App Passwords."
            )

            save_col, _ = st.columns([1, 3])
            with save_col:
                if st.button("💾 Save Configuration", type="primary"):
                    st.session_state.smtp_config = {
                        "server"  : new_server,
                        "port"    : int(new_port),
                        "username": new_username,
                        "password": new_password,
                        "from"    : new_from,
                        "use_tls" : new_tls,
                    }
                    write_env_file({
                        "EMAIL_SMTP_SERVER"  : new_server,
                        "EMAIL_SMTP_PORT"    : str(int(new_port)),
                        "EMAIL_SMTP_USERNAME": new_username,
                        "EMAIL_SMTP_PASSWORD": new_password,
                        "EMAIL_FROM"         : new_from or new_username,
                        "EMAIL_USE_TLS"      : "True" if new_tls else "False",
                    })
                    st.session_state.show_smtp_form = False
                    st.success("✅ Configuration saved to `.env` and will persist across refreshes.")
                    st.rerun()

    # ── Send Report ───────────────────────────────────────────────────────────
    st.markdown('<div class="section-title">Send Report</div>', unsafe_allow_html=True)

    recipient = st.text_input("Recipient email address:", placeholder="someone@example.com")

    if selected_pdf_name:
        portfolio_base = selected_pdf_name.replace("_Report.pdf", "")
        pdf_password   = portfolio_base[:8] if len(portfolio_base) >= 8 else portfolio_base
        st.info(
            f"📎 **{selected_pdf_name}** is password-protected.\n\n"
            f"**PDF Password:** `{pdf_password}` — included in the email body automatically."
        )

    send_disabled = (not selected_pdf) or (not recipient)
    send_btn = st.button("📤 Send Report by Email", type="primary", disabled=send_disabled)

    if send_btn:
        cfg = st.session_state.smtp_config   # always use latest saved config
        if not cfg["username"] or not cfg["password"]:
            st.error("SMTP username and password are not configured. Click **Edit Configuration** above.")
        elif not recipient or "@" not in recipient:
            st.error("Please enter a valid recipient email address.")
        else:
            try:
                from_addr      = cfg["from"].strip() or cfg["username"]
                portfolio_base = selected_pdf_name.replace("_Report.pdf", "")
                pdf_password   = portfolio_base[:8] if len(portfolio_base) >= 8 else portfolio_base

                msg = MIMEMultipart()
                msg["From"]    = from_addr
                msg["To"]      = recipient
                msg["Subject"] = f"{portfolio_base} Portfolio Report"

                body = (
                    f"Hello,\n\n"
                    f"Please find attached the latest portfolio report for {portfolio_base}.\n\n"
                    f"IMPORTANT – PDF PASSWORD REQUIRED:\n"
                    f"The PDF is password protected. Enter the following password when prompted:\n\n"
                    f"Password: {pdf_password}\n\n"
                    f"Regards,\nPortfolio Tracker"
                )
                msg.attach(MIMEText(body, "plain"))

                with open(selected_pdf, "rb") as attachment:
                    part = MIMEBase("application", "octet-stream")
                    part.set_payload(attachment.read())
                _encoders.encode_base64(part)
                part.add_header(
                    "Content-Disposition",
                    f"attachment; filename={selected_pdf_name}",
                )
                msg.attach(part)

                with st.spinner("Connecting to SMTP server…"):
                    server = smtplib.SMTP(cfg["server"], int(cfg["port"]))
                    server.ehlo()
                    if cfg["use_tls"]:
                        server.starttls()
                        server.ehlo()
                    server.login(cfg["username"], cfg["password"])
                    server.sendmail(from_addr, recipient, msg.as_string())
                    server.quit()

                st.success(f"✅ Report sent successfully to **{recipient}**!")
                st.balloons()

            except smtplib.SMTPAuthenticationError:
                st.error(
                    "Authentication failed. For Gmail, make sure you are using an **App Password** "
                    "(not your regular password)."
                )
            except smtplib.SMTPException as e:
                st.error(f"SMTP error: {e}")
            except Exception as e:
                st.error(f"Could not send email: {e}")


# ─── Footer ─────────────────────────────────────────────────────────────────
st.markdown("---")
st.markdown(
    f'<div style="text-align:center; color:{ACCENT}; font-size:0.8rem; font-family:Source Sans 3, sans-serif;">'
    f"NSE Portfolio Tracker · Data sourced from your Python script's output · "
    f"Prices from mansamarkets.com"
    f"</div>",
    unsafe_allow_html=True,
)
